Шаблонизируй это
htmlacademy-ecmascript/59826-big-trip-15 pull request #4
Opened 2021-08-06 21:11 UTC by lisabazdyreva

!!Посмотреть в form.js getDateTemplate. Проблемы с форматом отображения.
Созданы моки, компоненты отрисовываются на основании принятых данных.

2021-08-06 23:52 UTC, dtsaryov requested changes

2021-08-06 23:52 UTC, dtsaryov commented on src/main.js
> +  ['filter-past']: 'Past',
Квадратные скобки не нужны

2021-08-06 23:52 UTC, dtsaryov commented on src/main.js
> +  ['display-stats']: 'Stats',
Квадратные скобки не нужны

2021-08-06 23:52 UTC, dtsaryov commented on src/main.js
> +  ['sort-offer']: 'Offers',
Квадратные скобки не нужны

2021-08-06 23:52 UTC, dtsaryov commented on src/main.js
> +const POINTS = [];
Это не константа

2021-08-06 23:52 UTC, dtsaryov commented on src/mock/trip-point-consts.js
> +const TYPES = ['check-in', 'sightseeing', 'restaurant','taxi', 'bus', 'train', 'ship', 'drive', 'flight'];
Положи это (весь модуль) в модуль с моками, всё равно потом удалим

2021-08-06 23:52 UTC, dtsaryov commented on src/utils/random-value.js
> +const getRandomValue = (min, max, values = null) => {
Давай назовем модуль utils и будем сюда "складывать" все вспомогательные функции общего назначения

2021-08-06 23:52 UTC, dtsaryov commented on src/view/trip-route/filters.js
> +        <label class="trip-filters__filter-label" for="filter-everything">${FILTER_MODES['filter-everything']}</label>
Это не шаблонизация, т.к. в данном случае у нас нет никаких других данных, которые тут могут оказаться.

2021-08-06 23:52 UTC, dtsaryov commented on src/view/trip-route/menu.js
> +    <a class="trip-tabs__btn" href="#">${DISPLAY_MODES['display-stats']}</a>
Это тоже не нжно делать

2021-08-06 23:52 UTC, dtsaryov commented on src/view/trip-route/sorting.js
> +      <label class="trip-sort__btn" for="sort-day">${SORTING_MODES['sort-day']}</label>
И здесь подстановки не нужны

2021-08-06 23:52 UTC, dtsaryov commented on src/view/trip-route/trip-points-list.js
> +const isEditingForm = true;
Не нужен этот флаг, просто пока что отрисовываем одну форму и всё

2021-08-06 23:52 UTC, dtsaryov commented on src/view/trip-route/trip-points-list.js
> +  };
Здесь только сам шаблон должен быть. Точки и форму добавляем в main

2021-08-06 23:52 UTC, dtsaryov commented on src/view/trip-route/form.js
> +        <input class="event__input  event__input--time" id="event-end-time-1" type="text" name="event-end-time" value=${dateTo.format(DATE_FORMAT)}>
Нужно `${}` в кавычки обернуть и всё будет ок

2021-08-06 23:52 UTC, dtsaryov commented on src/view/trip-route/form.js
> +  }
Не понял, зачем это

2021-08-06 23:52 UTC, dtsaryov commented on src/view/trip-route/form.js
> +      <input id="event-type-${TYPES[i]}-1" class="event__type-input  visually-hidden" type="radio" name="event-type" value=${TYPES[i]} checked>
Все гораздо проще: 

```JS
${TYPES[i] === type && checked}

2021-08-06 23:52 UTC, dtsaryov commented on src/view/trip-route/form.js
> +  }
Не понял зачем

2021-08-06 23:52 UTC, dtsaryov commented on src/view/trip-route/form.js
> +      list="destination-list-1">`;
Не надо шаблоны дублировать

2021-08-06 23:52 UTC, dtsaryov commented on src/view/trip-route/form.js
> +  return options;
```JS
return DESTINATIONS.map((destination) => (`
  <option value="${destination}"></option>
`)).join('\n').trim();
```

2021-08-06 23:52 UTC, dtsaryov commented on src/view/trip-route/form.js
> +    </p>`);
Не надо настолько сильно мельчить

2021-08-06 23:52 UTC, dtsaryov commented on src/view/trip-route/form.js
> +  if (description !== undefined) {
А как связаны описание и фотографии?

Этот блок не отрисовывается, если пункта назначения нет

2021-08-06 23:52 UTC, dtsaryov commented on src/view/trip-route/form.js
> +    for(let i = 0; i < offers.length; i++) {
Д24. Для работы с JS-коллекциями используются итераторы для массивов.

2021-08-06 23:52 UTC, dtsaryov commented on src/view/trip-route/info.js
> +  }
Вообще говоря, точки у нас должны быть отсортированы в нужном порядке и достаточно взять первую и последнюю.

Это, кстати, одна из первых альтернатив твоему решению.

Вторая альтернатива - нужно всего две переменных для того чтобы найти минимум и максимум

2021-08-06 23:52 UTC, dtsaryov commented on src/view/trip-route/info.js
> +    if (POINTS[i].destination !== undefined) {
Такого не может быть

2021-08-06 23:52 UTC, dtsaryov commented on src/view/trip-route/info.js
> +      }
Почему бы при поиске сразу эти точки не найти и не использовать?

2021-08-06 23:52 UTC, dtsaryov commented on src/view/trip-route/info.js
> +  }
KISS :)

```JS
const text = cities.length > 3
  ? `${cities[0]} - ... - ${cities[cities.length - 1]}`
  : cities.join(' - ');
```

2021-08-06 23:52 UTC, dtsaryov commented on src/view/trip-route/info.js
> +  );
Ну и давай логику от отображения отделять

2021-08-06 23:52 UTC, dtsaryov commented on src/view/trip-route/info.js
> +};
Тоже надо разделить

2021-08-06 23:52 UTC, dtsaryov commented on src/view/trip-route/trip-point.js
> +    const FORMAT_TIME_ATTRIBUTE = 'YYYY-MM-DDTHH:mm';
Д17. Константы, используемые внутри функций, создаются вне функций и используются повторно через замыкания.

2021-08-06 23:52 UTC, dtsaryov commented on src/view/trip-route/trip-point.js
> +    const DIFFERENCE_MINUTES = MINUTES - (DIFFERENCE_HOURS * 60);
это не константы

2021-08-06 23:52 UTC, dtsaryov commented on src/view/trip-route/trip-point.js
> +    const FORMAT_DATE_ATTRIBUTE = 'YYYY-MM-DD';
Д17. Константы, используемые внутри функций, создаются вне функций и используются повторно через замыкания.

2021-08-06 23:52 UTC, dtsaryov commented on src/view/trip-route/trip-point.js
> +  if (type !== undefined) {
Этого не может быть

2021-08-07 09:27 UTC, lisabazdyreva commented on src/view/trip-route/filters.js
> +        <label class="trip-filters__filter-label" for="filter-everything">${FILTER_MODES['filter-everything']}</label>
А, можно же пройтись по объекту с значениями и возвращать на каждое разметку, верно? Это по этому пункту: 

6. Для оставшихся компонентов также перепишите функцию по созданию шаблона, чтобы она на вход принимала данные.

2021-08-07 17:56 UTC, dtsaryov commented on src/view/trip-route/filters.js
> +        <label class="trip-filters__filter-label" for="filter-everything">${FILTER_MODES['filter-everything']}</label>
Нет, здесь вообще ничего подобного не надо было делать - просто оставить статичную разметку.

Шаблонизация нужна только тогда, когда значения, используемые в шаблоне меняются от случая к случаю.

2021-08-07 17:56 UTC, dtsaryov commented on src/view/trip-route/filters.js
> +        <label class="trip-filters__filter-label" for="filter-everything">${FILTER_MODES['filter-everything']}</label>
И пиши, пожалуйста, вопросы в телегу, я с легкостью тут могу пропустить вопросы

2021-08-07 18:01 UTC, dtsaryov commented on src/view/trip-route/filters.js
> +        <label class="trip-filters__filter-label" for="filter-everything">${FILTER_MODES['filter-everything']}</label>
Сам с собой не договорился.

Без кода тут не обойдешься, но он нужен только для того, чтобы изменить визуальное отображение.

2021-08-07 18:04 UTC, merged